version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  execute_cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: create_or_update_stack
          command: |
            aws cloudformation create-stack --stack-name live-stack --template-body file://cloudformation/infrastructure.yml

workflows:
  live_workflow:
    jobs:
      - execute_cloudformation
